### ISSUE TITLE
Got a Error in knn.py file

### ISSUE THREAD

**Issue by Peararul** [anujdutt9/Handwritten-Digit-Recognition-using-Deep-Learning#18]
I got error while run the knn.py in cmd
![error](https://user-images.githubusercontent.com/106342342/171026763-5eaf6f3c-baf1-4240-96ee-d63a2a07e5c3.PNG)
![Dataset](https://user-images.githubusercontent.com/106342342/171026785-3779dd59-5748-4cc1-9f61-34ab75cd65cf.PNG)

I download files you mentionrd but I can't open it.

**Comment by anujdutt9** [comment]
Hi, can you extract the files from the attached zip folder and use these instead. Let me know if you still see the issue.
Hope this helps.
[dataset.zip](https://github.com/anujdutt9/Handwritten-Digit-Recognition-using-Deep-Learning/files/10738083/dataset.zip)
