### ISSUE TITLE
How to input testImages I have

### ISSUE THREAD

**Issue by Pramod07777** [anujdutt9/Handwritten-Digit-Recognition-using-Deep-Learning#2]
Hi anujdutt9 thank you for this awesome project,can you please help me on below..As i have converted my sample into MNIST DATASET Image after that i converted to grayscale still i got below error can you please revert on this.

Traceback (most recent call last):
  File "svm.py", line 88, in <module>
    test_labels_pred = clf.predict(im)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/svm/base.py", line 573, in predict
    y = super(BaseSVC, self).predict(X)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/svm/base.py", line 310, in predict
    X = self._validate_for_predict(X)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/svm/base.py", line 479, in _validate_for_predict
    (n_features, self.shape_fit_[1]))
ValueError: X.shape[1] = 800 should be equal to 784, the number of features at training time

**Comment by anujdutt9** [comment]
Hi @Pramod07777 . This is how you need to load your image file for classification task:

![code](https://user-images.githubusercontent.com/11924142/37543432-f223df38-2937-11e8-80dd-4432feabab5d.png)

Make sure to have the following imports:

import cv2
import numpy as np
import pickle
import matplotlib.pyplot as plt
from matplotlib import style
style.use('ggplot')

**Comment by CSALS** [comment]
How to convert our image into 28*28 image? Or could you tell me how to convert base64 image to 28*28 grayscale image?
