### ISSUE TITLE
How to detect digits other than in test image file

### ISSUE THREAD

**Issue by chowtaprathiksha** [anujdutt9/Handwritten-Digit-Recognition-using-Deep-Learning#4]
Hello,

I am new to machine learning.
I dont know how to predict images other than test images(new images) in KNN
Can someone help me how to do it?

Thanks in Advance.

**Comment by anujdutt9** [comment]
Hi. Please check out the solution to this issue to predict on images other than the test images.
https://github.com/anujdutt9/Handwritten-Digit-Recognition-using-Deep-Learning/issues/2
