### ISSUE TITLE
Convert base64 to MNIST image

### ISSUE THREAD

**Issue by CSALS** [anujdutt9/Handwritten-Digit-Recognition-using-Deep-Learning#5]
How to convert the base64 image which we get from HTML canvas to image compatible with our model i.e. 28*28 grayscale image? I have tried many resources but none of them were able to produce correct results.

**Comment by anujdutt9** [comment]
Hi. Can you give me some example data for this or maybe share some code so that I can see where exactly you are having the issue ?

**Comment by anujdutt9** [comment]
Closing issue due to no further response.
